
apiVersion: v2
name: tezos-markeplace-indexer
version: 0.1.0
dependencies:
- name: rarible-helm-chart
  alias: tezos-marketplace-indexer-rarible
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: tezos-marketplace-indexer-tezos
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: tezos-marketplace-indexer-metadata
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: aux-tezos-marketplace-indexer-rarible
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: hasura
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: aux-hasura
  repository: file://../resources/helm/rarible
  version: 0.1.0