hasura:
  service:
    nodePort: 30339

tezos-marketplace-indexer-rarible: &tezos-marketplace-indexer-dev
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    HASURA_URL: http://hasura:8080
    NETWORK: ghostnet
  resources:
    limits:
      cpu: '1'
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi

tezos-marketplace-indexer-metadata: *tezos-marketplace-indexer-dev

tezos-marketplace-indexer-royalties: *tezos-marketplace-indexer-dev

tezos-marketplace-indexer-ophash:
  enabled: false
  replicas: 0

tzkt:
  network: ghostnet
  service:
    nodePort: 30340
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.dev.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http
