hasura:
  service:
    nodePort: 30339

tezos-marketplace-indexer:
  environments: 
    TZKT_URL: http://tzkt:5000

tzkt:
  enabled: true
  network: privatenet
  service:
    nodePort: 30340
  environments:
    TezosNode__Endpoint: http://dev-node.tezos-node:8732/
    TokenMetadata__DipDup__Url: http://hasura:8080/v1/graphql