hasura:
  service:
    nodePort: 30339

tezos-marketplace-indexer-rarible: &tezos-marketplace-indexer-dev
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    HASURA_URL: http://hasura:8080
    NETWORK: ghostnet
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi

tezos-marketplace-indexer-tezos: *tezos-marketplace-indexer-dev

tezos-marketplace-indexer-metadata: *tezos-marketplace-indexer-dev

aux-hasura:
  replicas: 0
  enabled: false

aux-tezos-marketplace-indexer-rarible:
  replicas: 0
  enabled: false

tzkt:
  network: ghostnet
  service:
    nodePort: 30340
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.dev.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http
